version: "3.3"
services:
  nginx:
    image: nginx:1.23
    ports:
      - "8080:80"
    volumes :
      - ./app:/app
      - ./site.conf:/etc/nginx/conf.d/site.conf
  php:
    build : .
    volumes :
      - ./app:/app
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports :
      - "3306:3306"    
