name: deploy
on: [push]
jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: deploy last version to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd ~/docker-lemp
          echo ${{ secrets.PASSWORD }} | sudo -S docker-compose down
          sudo 
          git pull
          echo ${{ secrets.PASSWORD }} | sudo -S docker-compose up -d
